### ISSUE TITLE
Tarea6

### ISSUE THREAD

**Issue by ericknegreter** [UG-OS2016/Tareas#1]
Buenas tardes profesor y compañeros, veran mi duda es respecto a cuales son los puntos que debemos de buscar acerca de la tarea 6 pues no comprendí del todo bien que es lo que debemos reportar en dicha tarea. De ante mano gracias.

**Comment by tzohpilotl** [comment]
La verdad es que no sé en qué consiste la tarea 6, no está anunciada ni especificada.

**Comment by JuanCrg90** [comment]
Tareas actualizadas. Sorry se me paso. solo es investigación

**Comment by tzohpilotl** [comment]
¿El contenido de la tarea 6 va a incluirse en el examen?

**Comment by JuanCrg90** [comment]
así es.

_Juan Carlos Ruiz GonzálezSitio Web http://juancrg90.me/ | *_Twitter
https://twitter.com/juancrg90 | Linkedin
https://www.linkedin.com/in/juancrg90 | Github
http://github.com/JuanCrg90*

2016-03-05 19:24 GMT-06:00 Alejandro Lázaro notifications@github.com:
